name: nofap
description: "A new Flutter project — habit tracker with rewards & great UI"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State management + routing (GetX is required)
  get: ^4.7.1
  google_nav_bar:
  curved_navigation_bar: 

  # Local storage for tracking streaks, rewards, settings
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Local notifications to remind users (schedule rewards/notifications)
  flutter_local_notifications: ^19.4.0

  # Nice UI: Google Fonts + SVG support for crisp icons
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  supabase_flutter: 
  cupertino_icons: 

  # Progress / percentage widgets for streak UI
  percent_indicator: ^4.2.5
  smooth_page_indicator: ^1.2.0
  lottie: ^3.1.3

  # Celebration / reward effect (confetti)
  confetti: ^0.8.0

  # Useful small helpers
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
    - Assets/level-up-04-243762.mp3

  fonts:
    - family: Chillax
      fonts:
        - asset: Assets/Chillax-Regular.ttf
